[mainnet]
endpoint_url = "${MAINNET_RPC_URL}"

[mainnet.bool]
is_testnet = false

[sepolia]
endpoint_url = "${SEPOLIA_RPC_URL}"

[sepolia.bool]
is_testnet = true

[optimism]
endpoint_url = "${OPTIMISM_RPC_URL}"

[optimism.bool]
is_testnet = false

[optimism-sepolia]
endpoint_url = "${OPTIMISM_SEPOLIA_RPC_URL}"

[optimism-sepolia.bool]
is_testnet = true

[bsc]
endpoint_url = "${BSC_RPC_URL}"

[bsc.bool]
is_testnet = false

[bsc-testnet]
endpoint_url = "${BSC_TESTNET_RPC_URL}"

[bsc-testnet.bool]
is_testnet = true

[unichain]
endpoint_url = "${UNICHAIN_RPC_URL}"

[unichain.bool]
is_testnet = false

[unichain-sepolia]
endpoint_url = "${UNICHAIN_SEPOLIA_RPC_URL}"

[unichain-sepolia.bool]
is_testnet = true

[polygon]
endpoint_url = "${POLYGON_RPC_URL}"

[polygon.bool]
is_testnet = false

[amoy]
endpoint_url = "${AMOY_RPC_URL}"

[amoy.bool]
is_testnet = true

[base]
endpoint_url = "${BASE_RPC_URL}"

[base.bool]
is_testnet = false

[base-sepolia]
endpoint_url = "${BASE_SEPOLIA_RPC_URL}"

[base-sepolia.bool]
is_testnet = true

[arbitrum]
endpoint_url = "${ARBITRUM_RPC_URL}"

[arbitrum.bool]
is_testnet = false

[arbitrum-sepolia]
endpoint_url = "${ARBITRUM_SEPOLIA_RPC_URL}"

[arbitrum-sepolia.bool]
is_testnet = true

[avalanche]
endpoint_url = "${AVALANCHE_RPC_URL}"

[avalanche.bool]
is_testnet = false

[fuji]
endpoint_url = "${FUJI_RPC_URL}"

[fuji.bool]
is_testnet = true

[linea]
endpoint_url = "${LINEA_RPC_URL}"

[linea.bool]
is_testnet = false

[linea-sepolia]
endpoint_url = "${LINEA_SEPOLIA_RPC_URL}"

[linea-sepolia.bool]
is_testnet = true

[scroll]
endpoint_url = "${SCROLL_RPC_URL}"

[scroll.bool]
is_testnet = false

[scroll-sepolia]
endpoint_url = "${SCROLL_SEPOLIA_RPC_URL}"

[scroll-sepolia.bool]
is_testnet = true